# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'YelpApp' do
  pod 'AFNetworking', '2.2.1'
  pod 'BDBOAuth1Manager', '1.2.0'
  pod 'SVProgressHUD'
end

target 'YelpAppTests' do

end

